Make clear when to use trento-premium package
SUSE/doc-slesforsap pull request #113
Opened 2022-03-01 13:18 UTC by tomschr

The Trento premium installation package is available for customer that don't have a Kubernetes in place and want to deploy it on K3s on SLES for SAP.

---

After the PR is merged, cherry-pick to `maintenance/15-SP3`.

2022-03-02 15:09 UTC, ajaeger requested changes

2022-03-02 15:09 UTC, ajaeger commented on xml/article_sap_trento.xml
> +      package, install Trento on your &t.server; host as follows: </para>
I would say something like: The trento-premium-server-installer simplifies the installation and installs K3s and helm for you, so it replaces the following manual steps.

2022-03-03 09:58 UTC, abravosuse reviewed
I don't know how to make references to specific steps or sections.

2022-03-03 14:10 UTC, abravosuse commented
@tomschr I've made a suggestion on this PR following your approval request. Do I need to Commit the suggestion? Thx!

2022-03-08 16:19 UTC, abravosuse commented
Just following up on this PR @tomschr. Do you need me to commit my suggestion so that you can review it?

2022-03-15 12:08 UTC, tomschr commented
@abravosuse Thank you for the suggestions. I've created references to the specific steps in commit ae9821b.

2022-03-15 13:42 UTC, ajaeger requested changes

2022-03-15 13:42 UTC, ajaeger commented on xml/article_sap_trento.xml
> +      want to deploy the server on K3s for &productname;.
LInes 308+309 have nothing todo with 310 and 311. Do you want to delete the whole paragraph?

2022-03-22 09:30 UTC, merged